CREATE DATABASE HOSPITAL;
USE HOSPITAL;

CREATE TABLE IF NOT EXISTS PACIENTES(
CPF_PACIENTE VARCHAR(15) PRIMARY KEY,
NOME VARCHAR(45) NOT NULL,
DATA_NASC DATE NOT NULL,
TELEFONE VARCHAR(45) NOT NULL,
EMAIL VARCHAR(45));

CREATE TABLE IF NOT EXISTS DEPARTAMENTOS(
COD_ESPECIALIDADE INT PRIMARY KEY,
NOME_ESPECIALIDADE VARCHAR(45));

CREATE TABLE IF NOT EXISTS MEDICOS(
CRM INT,
UF CHAR(2),
PRIMARY KEY(CRM,UF),
NOME VARCHAR(45) NOT NULL,
EMAIL VARCHAR(45) NOT NULL,
TELEFONE VARCHAR(45) NOT NULL,
DEPTO_COD_ESPEC INT NOT NULL,
CONSTRAINT DEPTO_MED FOREIGN KEY(DEPTO_COD_ESPEC)REFERENCES DEPARTAMENTOS(COD_ESPECIALIDADE));

CREATE TABLE IF NOT EXISTS CONSULTAS(
ID_CONSULTA INT PRIMARY KEY,
ANAMNESE TEXT NOT NULL,
DATA_CONS DATE NOT NULL,
HORA_CONS TIME NOT NULL,
CRM INT NOT NULL,
UF CHAR(2) NOT NULL,
CPF_PACIENTE VARCHAR(15) NOT NULL,
CONSTRAINT MED_CONS FOREIGN KEY(CRM,UF) REFERENCES MEDICOS(CRM,UF),
CONSTRAINT PAC_CONS FOREIGN KEY(CPF_PACIENTE)REFERENCES PACIENTES(CPF_PACIENTE));

INSERT INTO PACIENTES
 (CPF_PACIENTE, NOME, DATA_NASC, TELEFONE, EMAIL)
VALUES
("111.111.111-22", "CAIQUE BARBOSA", 2006-02-18, "+55279996587488", "BLABLA@GMAIL.COM" );
INSERT INTO DEPARTAMENTOS
(COD_ESPECIALIDADE, NOME_ESPECIALIDADE)
VALUES 
(1,"CARDIOLOGIA"),
(2, "PEDIATRIA"),
(3, "GINECOLOGIA");

INSERT INTO MEDICOS
(CRM, UF, NOME, EMAIL, TELEFONE, DEPTO_COD_ESPEC)
VALUE 
("4002-8922", "ES", "FLAVIN DO PNEU", "DOPNEU@GMAIL.COM", "4002-8922", "NOT NULL");

INSERT INTO CONSULTAS
(ID_CONSULTA,ANAMNESE, DATA_CONS, HORA_CONS, CRM , UF, CPF_PACIENTE)
VALUES
("QWE123", "BLABLABLABLA", "18-02-2006", "15:00", "4002-8922", "ES", "111.111.111-55")



